### ISSUE TITLE
能否增加更新ck或者wsck的时候自动启用

### ISSUE THREAD

**Issue by 21ki** [huiyi9420/ninja#1]
如果有个ck过期被仅禁用了,然后更新完之后不会自动启用

**Comment by huiyi9420** [comment]
我试试吧

**Comment by huiyi9420** [comment]
> 如果有个ck过期被仅禁用了,然后更新完之后不会自动启用

请更新或者重新拉取项目，已解决你说的问题
现已实现更新wskey或者ck后启用账号一次
